services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalog
    # ports: ["3306:3306"]
    volumes: [db_data:/var/lib/mysql]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  backend:
    build: ../backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: catalog
    depends_on:
      db:
        condition: service_healthy
    ports: ["3000:3000"]

  seed:
    build: ../backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: catalog
    depends_on:
      db:
        condition: service_healthy
    command: ["node", "dist/src/seeds/seed.js"]

  frontend:
    build: ../frontend
    ports: ["5173:80"] # Vite build servido pelo nginx
    depends_on: [backend]

volumes:
  db_data:
